### ISSUE TITLE
Margin right after Red color

### ISSUE THREAD

**Issue by HZooly** [mc-astro/tesla-roadster-colors#1]
I think this is your choice, but why did you decide to set margin after red color pick?

`.red{background-color: #c31130; margin-right: 30px;}`

By the way, this is a great visual! :fire:

**Comment by mc-astro** [comment]
It's to separate the "official tesla's colors" until now, from those proposed by me.
but thanks to your comment I've realized that people can see it as a bug.

I've narrowed the gap between the two blocks
http://take.ms/AxEDp

Thank you for your comment
Highly appreciated 🙌   ❤️

**Comment by HZooly** [comment]
Ok, I wasn't sure about the reason!

Anyway, great job, keep it up 🚔

**Comment by mc-astro** [comment]
Many thanks!
